### ISSUE TITLE
linotte 3 : crash "An illegal reflective access operation has occurred"

### ISSUE THREAD

**Issue by farvardin** [cpc6128/LangageLinotte#13]
bonjour,

j'ai téléchargé linotte 3 (Linotte_3.2-2020-09-23-18-49.zip) et lorsque je le démarre avec java -jar Atelier.jar j'ai bien l'écran de démarrage, et ensuite ça plante en indiquant en console :  

> WARNING: An illegal reflective access operation has occurred
> WARNING: Illegal reflective access by javax.media.j3d.JoglPipeline (file:/opt/linotte/Atelier.jar) to method sun.awt.AppContext.getAppContext()
> WARNING: Please consider reporting this to the maintainers of javax.media.j3d.JoglPipeline
> WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
> WARNING: All illegal access operations will be denied in a future release
> Inconsistency detected by ld.so: dl-lookup.c: 111: check_match: Assertion `version->filename == NULL || ! _dl_name_match_p (version->filename, map)' failed!

Je suis sous linux mint 19.3, et ma version de java : 

> java --version
>openjdk 11.0.8 2020-07-14
>OpenJDK Runtime Environment (build 11.0.8+10-post-Ubuntu-0ubuntu118.04.1)
>OpenJDK 64-Bit Server VM (build 11.0.8+10-post-Ubuntu-0ubuntu118.04.1, mixed mode, sharing)

**Comment by cpc6128** [comment]
Hello @farvardin !
Ah oui, je l'ai pas testé cette version sur Linux. 
En effet, java 3D n'est plus supporté par Oracle, du coup, je passe par une autre librairie mais la version que j'utilise n'est pas encore stable.
Je vais faire en sorte que l'Atelier se lance même si la librairie ne fonctionne pas sur le système.
Merci

**Comment by cpc6128** [comment]
@farvardin 
Peux-tu me dire ça fonctionne mieux avec cette version :

linotte-dist-3.3-20201005.185614-1.zip

depuis ce lien : https://github.com/cpc6128/LangageLinotte/packages/393278

**Comment by farvardin** [comment]
salut Ronan, désolé, je n'avais pas vu plus tôt la notification de ta réponse...

J'ai essayé cette version 3.3, et cela indique exactement la même erreur.

Après, pour j3d c'est juste un warning, là où ça semble bloquer c'est la partie avec ld.so... mais c'est peut-être lié.

**Comment by farvardin** [comment]
je viens d'essayer sur un autre ordinateur (linux mint 19.3 aussi), et linotte3.3 fonctionne dessus ! D'ailleurs sur cet autre PC, linotte 3.1 fonctionne également. (Le premier pc, qui ne fonctionne pas, utilise une carte nvidia, le second une carte ati)

**Comment by cpc6128** [comment]
Merci Eric pour ton analyse. En effet, ce matin, j'ai aussi testé sur une Ubuntu 18 et ça marche. J'ai l'impression que c'est lié à la version du jdk (openjdk). A l'occasion, je veux que tu tests la version 3.1 sur le pc qui pose problème. Merci !

**Comment by farvardin** [comment]
@cpc6128 Oui, je viens de trouver une info à ce sujet : https://stackoverflow.com/questions/55847497/how-do-i-troubleshoot-inconsistency-detected-dl-lookup-c-111-java-result-12

Sur le premier PC (ne fonctionne pas) la version installée était openjdk 11 (y'avait la 8 et la 11 mais c'était la 11 qui était activée)
Sur le second PC (fonctionne), idem, les 2 versions d'installée, mais c'est la version 8 de openjdk qui était activée. 

J'ai désintallé openjdk 11 sur le premier PC, et maintenant tout fonctionne correctement ! Merci. Par contre sur ce premier pc j'avais déjà déinstallé openjdk11 avant de voir ton message pour tester linotte 3.1. Mais vu que la 3.2 bloquait également, ça devait être pareil.

**Comment by cpc6128** [comment]
A suivre : 
https://bugs.launchpad.net/ubuntu/+source/gcc-7/+bug/1764701

**Comment by cpc6128** [comment]
Je propose maintenant une version sans la 3D qui devrait fonctionner.

**Comment by cpc6128** [comment]
La 3D a été supprimée dans la dernière release.
