### ISSUE TITLE
Documentation en ligne : préciser la version

### ISSUE THREAD

**Issue by farvardin** [cpc6128/LangageLinotte#19]
Après l'installation de linotte 3, je suis en train de parcourir la documentation pour en savoir plus. Seulement, beaucoup d'informations dans la doc concernent la version 2, du coup des exemples donnés ne sont plus compatibles. Ce n'est pas forcément un problème, mais ça serait bien de savoir ce qui cible la version 2 et ce qui cible la version 3, notamment parce que quand on clique sur le lien pour la doc depuis l'atelier 3, on arrive sur la page de doc générique, et si on lit ce document on ne peut pas utiliser les exemples : http://langagelinotte.free.fr/linotte/10minutes/10minutes20.html

De ce que je peux voir d'ailleurs, il n'y a pas de doc officielle sur linotte 3, il faut s'aider des exemples pour voir ce qu'il en est. Peut-être qu'il serait bien d'indiquer par exemple : 

## Linotte 3 

_doc à venir_

## Linotte 2

* Présentation : PdfLes bases syntaxiques ou découvrir Linotte en 10 minutes
* Tutoriel : PdfDécouvrir la programmation avec le langage Linotte par Wam
* Présentation en vidéo 1 : HTML Présentation de l’atelier de programmation du langage Linotte

etc

**Comment by cpc6128** [comment]
En effet, ça va être mon prochain chantier. Je pense que le langage est maintenant stable et cohérent. Je vais moins le modifier. Je vais me concentrer sur la doc.
Je pense utiliser le wiki de github : https://github.com/cpc6128/LangageLinotte/wiki
Je ferai pointer l'Atelier vers ce lien dans les prochaines versions.

Je vais également ajouter d'autres vidéos sur youtube.

**Comment by XP-Rico** [comment]
Je suis en train de refaire une documentation sur Linotte version 3.9. J'ai déjà terminé les notions de bases, et j'espère finir le reste pour début 2022.

**Comment by XP-Rico** [comment]
https://mega.nz/file/KvhTBSiY#9TofaOZmAk7ZgZr-c8WxZnrgv487pa9U0-GKGhyKyIk 

Voici le lien pour les notions de bases de programmation Linotte version 3.9

**Comment by cpc6128** [comment]
Merci @XP-Rico , j'ai ajouté le document sur la page officiel de la documentation Linotte !
https://github.com/cpc6128/LangageLinotte/wiki
Un grand merci.

**Comment by cpc6128** [comment]
Je ferme ce ticket car la page documentation classe les exemples par "grandes versions" du langage.
