### ISSUE TITLE
Is this possible to use opengl to do more complex graphics ?

### ISSUE THREAD

**Issue by Ornito** [cpc6128/LangageLinotte#38]
Hi! I like this langage but unfortunately I can't use it because I need to perform more complex graphics with the opengl library, and also using templates, reflexibility, serialization and so on so actually my project is codded in c++.

**Comment by Ornito** [comment]
Oups j'ai écrit en Anglais, tête de Linotte.

**Comment by cpc6128** [comment]
Ouf, je peux répondre en français :) 
Malheureusement non , j'ai commencé à ajouté des fonctionnalités avec Java3d mais je rencontre des problèmes de compatibilité avec les dernières version des jdk.

**Comment by Ornito** [comment]
Ah dommage, pas adapté pour ce que je veux faire donc ce langage, de plus moins rapide que le c++ le java, parce qu'il me semble qu'en java on ne peut pas utiliser CRTP pour faire du polymorphisme statique, ni de templates variadiques, mais des fonctions virtuelles qui ont un coût à l'exécution, ce lien montre la différence au niveau des performances, les fonctions virtuelles sont 3.9 fois plus lente.
[benchmark](https://quick-bench.com/q/c5l442vA4CoGi_PBCFP2ibm0wts)
Utilise le c++ ou si tu veux rester en java utilise JOGL.

**Comment by Ornito** [comment]
Le défaut de ce système est qu'il faut passer chaque type au parameter pack donc si il y en a beaucoup ça devient ingérable, mais tu as implémenté une fonctionnalité qui est je trouve vraiment intéressante et que je ne retrouve pas dans le langage c++, ni même dans le language java avec le verbe attacher qui permet justement de résoudre ce problème.

**Comment by cpc6128** [comment]
Bonjour @Ornito , 
en effet, j'utilise le principe des prototypes pour attacher des méthodes aux instances des "objets" du langage. ça me permet d'ajouter des fonctionnalités au langage.
Mais j'ai l'impression que le langage est trop simple pour tes besoins ?

**Comment by Ornito** [comment]
Oui probablement.

**Comment by Ornito** [comment]
J'utilise aussi cette technique en c++ je fais même encore quelque chose de plus complexe pour attacher un nouveau type à un conteneur. 

    sphere sph;
    sph.managerName="entity managers";
    rectangle rect;
    rect.managerName="entity managers";
    convexshape shape;
    shape.managerName="entity managers";

    RenderWindow rw(sf::VideoMode(800, 600), "test");
    ::EntityManager<entity> ems;
    ems.name = "entity managers";
    ::EntityManager<entity> childrenem;
    childrenem.name = "sphere children manager";
    ::EntityManager children0em = sph.addChild(childrenem, &shape);
    ::EntityManager em = ems.add(&sph).add(&rect);
    EntityManagerArray<IEntityManager> ema;
    EntityManagerArray emas = ema.add(&em).add(&children0em);
    emas.move(&sph);

Je dois juste "redéclarer" le conteneur vu que son type change lorsque j'ajoute un nouveau type et je ne peux pas le stocker dans une variable membre parce que son type change mais ça ce n'est pas grave, il suffise que je le passe à chaque fonctions qui l'utilise. 
Cela me permet juste, d'utiliser le polymorphisme statique, plus performant que le polymorphisme dynamique avec les fonctions virtuelles et de ne pas être obligé de déclarer tout les types en compilation pour les template variadiques ce qui serait lourd si il y en a beaucoup. 

Et voici ou j'attache une fonction membre à une instance d'un objet de mon framework  : 

struct entity : transformable {
        unsigned int id;
        static unsigned int nbEntities;
        std::string managerName;
        entity() : transformable () {
            id = nbEntities;
            nbEntities++;
        }
        template <typename D, typename EntityManager>
        auto addChild(EntityManager em, D* entity) {
            auto newem = em.add(entity);
            children = ::FastDelegate<void>(&decltype(newem)::moveAll, newem);
            return newem;
        }
        template<typename D>
        void move(D* entity) {
          std::cout<<"move entity of instance : "<<id<<std::endl;
          transformable::move<D>();
          children();
        }
        ::FastDelegate<void> children;
    };
Plutôt que de stocker le conteneur qui change de type je stocke un pointer de fonction sur le nouveau type.
Bref ce que je dois faire, est vraiment trop complexe pour le faire en Linotte, c'est dommage, j'aime bien ce langage, j'ai un grand besoin de performance.


Je me demande en Linotte, si on peut attacher un nouveau type à une espèce se trouvant dans un casier, je n'ose même pas imaginer ce que ça provoquerait comme comportement de changer une structure de données à l'exécution.

**Comment by cpc6128** [comment]
Pour les prototypes, voici un exemple simple :
https://github.com/cpc6128/LangageLinotte/blob/develop/linotte-resources/src/main/exemples/plus_d_exemples_ici/j_expert/acteurs_prototype.liv

Après, comme j'indique dans l'exemple, je ne documente plus cette syntaxe. Ce n'est pas la cible des utilisateurs du langage. Je me suis juste fait plaisir !

Et pour répondre à ta dernière question, oui, on peut modifier une espère ou acteur dynamiquement. Du coup, on peut tomber sur des erreurs :

```
c est un casier de nombre valant 1, 2, 3
attache addition à c{0}
attache addition à c{1}
pour c affiche joker.addition(10)

addition : n
	moi prend n + moi
	retourne moi
```

**Comment by Ornito** [comment]
Je me disais bien parce que si un composant X (dans un casier) contient un composant Y et que l'on change la taille du composant Y, la taille du composant X en mémoire change et donc la taille du casier change.

**Comment by Ornito** [comment]
C'est comme si en c++ on pouvait changer le type d'une variable ce que le c++ ne permet pas de faire et le java non plus d'ailleurs, sans quoi il faudrait changer la taille de tout les objets instanciés à l'exécution

**Comment by cpc6128** [comment]
Bonjour,
Je ferme ce ticket.
La 3D a été supprimée du langage.
